### PR TITLE
Display stats during replay

### LINKED ISSUE #27: Display stats during replay
Currently, you can see the stats only when the test or replay has finished.
image

But during the replay there is no way of knowing what the stats were.

When user hits enter to replay, we should display the stats at the bottom of the screen on the last line.

It feels like some other position like top right would have worked as well, but that is because we only have 1 stat currently.
But very soon we will be having a few more (see #16 ) , so last line seems feasible.

### PR DESCRIPTION
**Pull request by RiturajJain**
This PR fixes #27.

### CODE REVIEW

**Comment by Mithil467** [comment]
Hey @RiturajJain :wave:

Thanks for the PR!

**Comment by Mithil467** [comment]
image

The line press enter to see a replay! shouldn't be visible while the replay is happening.

**Comment by RiturajJain** [comment]
Hey @Mithil467,

Sorry, for this silly mistake. I have made the required changes.

**Comment by Mithil467** [comment]
No problem! @RiturajJain 
This works great :)

Thank you for the fix! 👍🏼

**Pull request merged**
