### PR TITLE
Use with statements to open files

### LINKED ISSUE #92: Open files using `with` statement
It is a good idea to use `with open(filename) as f:` instead of using a combination of `open` and `close`. 
Python ensures the resources are closed with the context.

The files to be changed are -

- [ ] history.py
- [ ] commandline.py

### PR DESCRIPTION
**Pull request by VivekThazhathattil**
This PR fixes #92

Tested with python version - 3.9.6

On operating system - Arch Linux

* both history.py and commandline.py changed
* ~~added header 'ACCURACY' for the last column in the output of `mitype -H`~~

### CODE REVIEW

**Review by Mithil467 — CHANGES_REQUESTED** [review]
Hey @VivekThazhathattil thanks for the PR!
Please don't add accuracy related code in this PR, a separate issue will be opened for that, and a few things are to be taken care of about the transition.
Please have a look at the contributing guidelines!

**Comment by VivekThazhathattil** [comment]
Sorry, my bad! I've removed the accuracy related code.

**Comment by Mithil467** [comment]
While reviewing this PR carefully, I noticed that the accuracy was being stored in the history file, and only the header was missing.
As far as I knew, the accuracy was never stored and hence I also had added this as a todo in [Project plan](https://github.com/Mithil467/mitype/projects/1).
I request you to add it again as adding the header was very much needed to solve this inconsistency.
You may also just remove the last commit instead using -
```
git reset --hard HEAD~1
git push -f
```

**Comment by VivekThazhathattil** [comment]
May be I can open another PR specifically for adding accuracy? Let this PR be for just fixing the linked issue.

**Comment by Mithil467** [comment]
That will be great! :)

**Pull request merged**
