### PR TITLE
Sphinx Updates

### LINKED ISSUE #53: Fix Sphinx documentation
Since mitype is seeing some docstring improvements (#52), it would be a good time to also work on the sphinx documentation.

Currently the Sphinx setup lies in [docs](https://github.com/Mithil467/mitype/tree/master/docs) folder.

There were several changes to the project like moving from `README.rst` to `README.md` and the setup is very outdated.

### PR DESCRIPTION
**Pull request by Jitsusama**
This PR fixes #53. At least I believe it does. Please review and let me know if anything falls short. The Internal API documentation will of course be more useful once #51 is merged as well.

Tested with python version - 3.8
On operating system - macOS

### CODE REVIEW

**Comment by Mithil467** [comment]
Works perfectly! :)

Currently there are lots of warnings when running `make html`. Can these be reduced or fixed completely somehow?

**Review by Mithil467 — APPROVED** [review]

**Comment by Jitsusama** [comment]
> Works perfectly! :)
> 
> Currently there are lots of warnings when running `make html`. Can these be reduced or fixed completely somehow?

I run warning free. would you mind sending me what you are seeing and I’ll try to figure out what is happening? It might be the version of Sphinx you are using. I downloaded the latest. Try ‘pip upgrade sphinx’ maybe and see if that runs clean?

**Comment by Mithil467** [comment]
I get the following output upon running `make html` from within docs.
```
Running Sphinx v2.2.2
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 0 added, 4 changed, 0 removed
reading sources... [100%] usage                                                                                                                                          
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.app, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:7: WARNING: duplicate object description of mitype.app.App, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:13: WARNING: duplicate object description of mitype.app.App.appendkey, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:22: WARNING: duplicate object description of mitype.app.App.check_word, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:28: WARNING: duplicate object description of mitype.app.App.erase_key, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:34: WARNING: duplicate object description of mitype.app.App.get_dimensions, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:47: WARNING: duplicate object description of mitype.app.App.initialize, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:56: WARNING: duplicate object description of mitype.app.App.key_printer, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:70: WARNING: duplicate object description of mitype.app.App.keyinput, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:82: WARNING: duplicate object description of mitype.app.App.main, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:93: WARNING: duplicate object description of mitype.app.App.replay, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:102: WARNING: duplicate object description of mitype.app.App.reset_test, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:108: WARNING: duplicate object description of mitype.app.App.resize, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:117: WARNING: duplicate object description of mitype.app.App.setup_print, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:126: WARNING: duplicate object description of mitype.app.App.size_error, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:133: WARNING: duplicate object description of mitype.app.App.typing_mode, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:144: WARNING: duplicate object description of mitype.app.App.update_state, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:153: WARNING: duplicate object description of mitype.app.App.word_wrap, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.calculations, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:7: WARNING: duplicate object description of mitype.calculations.first_index_at_which_strings_differ, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:25: WARNING: duplicate object description of mitype.calculations.get_space_count_after_ith_word, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:39: WARNING: duplicate object description of mitype.calculations.number_of_lines_to_fit_string_in_window, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:53: WARNING: duplicate object description of mitype.calculations.speed_in_wpm, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.commandline, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:9: WARNING: duplicate object description of mitype.commandline.display_version, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:15: WARNING: duplicate object description of mitype.commandline.load_based_on_difficulty, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:29: WARNING: duplicate object description of mitype.commandline.load_from_database, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:41: WARNING: duplicate object description of mitype.commandline.load_text_from_file, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:53: WARNING: duplicate object description of mitype.commandline.main, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:62: WARNING: duplicate object description of mitype.commandline.parse_arguments, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.database, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:7: WARNING: duplicate object description of mitype.database.database_file_absolute_path, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:19: WARNING: duplicate object description of mitype.database.fetch_text_from_id, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.keycheck, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:7: WARNING: duplicate object description of mitype.keycheck.is_backspace, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:27: WARNING: duplicate object description of mitype.keycheck.is_enter, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:39: WARNING: duplicate object description of mitype.keycheck.is_escape, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:59: WARNING: duplicate object description of mitype.keycheck.is_null, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:71: WARNING: duplicate object description of mitype.keycheck.is_resize, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:83: WARNING: duplicate object description of mitype.keycheck.is_valid_initial_key, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:2: WARNING: duplicate object description of mitype.timer, other instance in mitype, use :noindex: for one of them
/home/mithil/p/mitype/docs/source/api.rst:7: WARNING: duplicate object description of mitype.timer.get_elapsed_minutes_since_first_keypress, other instance in mitype, use :noindex: for one of them
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/mithil/p/mitype/docs/source/modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] usage                                                                                                                                           
generating indices...  genindex py-modindexdone
highlighting module code... [100%] mitype.timer                                                                                                                          
writing additional pages...  searchdone
copying images... [100%] _static/demo.gif                                                                                                                                
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 43 warnings.

The HTML pages are in build/html.
```

**Comment by Mithil467** [comment]
Hey @Jitsusama I guess there must be some mistake on my end, I got it working after having a clean branch. My bad for the false positive. This seems working fine!

**Comment by Mithil467** [comment]
Let's merge this! ❤️ 
This was something I was slacking off over a very long time. I really appreciate your initiative in resolving this issue and making the docs brand new!
This is finally possible due to your efforts :)

Thank you very much! @Jitsusama

**Comment by Jitsusama** [comment]
You’re most welcome, so glad to help!

**Pull request merged**
