### PR TITLE
Fix visual glitch when using backspace to clear text on multiple rows

### LINKED ISSUE #59: Visual glitch when using backspace to clear text on multiple rows
### Steps to reproduce:
Start mitype, preferably with a relatively lesser width terminal window.
Spam any wrong keys so that the text overflows to next line as shown below.
image
Try to clear those keys by pressing backspace.
image

### Expected behaviour
Backspace should clear all the keys consistently.

### Actual behaviour
The logic works as expected and does indeed clear text but doesn't update the screen visually for the lines below, but works fine for top line.

### Proposed fix
Maybe we need to clear the entire screen if that is feasible.

### PR DESCRIPTION
**Pull request by sks147**
This PR fixes #59 

Tested with python version - 2.7.16, 3.8.5

On operating system - macOS Catalina, Version 10.15.7

### CODE REVIEW

**Comment by Mithil467** [comment]
The issue will still persist when user moves further down on the next line. Clearing each line individually won't help in this case.
I'd suggest the following - 
whenever backspace key is hit, calculate the amount of lines required to print the `current_string` on the console. And based on the count, clear that many lines. Have a look at the `number_of_lines_to_fit_text_in_window` function and pass `current_string` to the function and act accordingly.

Feel free to ask if having doubts :)

**Comment by jai-dewani** [comment]
If I can understand currently, `current_word` is being printed and we should calculate the number of lines needed to print it and clear those many lines instead of directly clearing `self.line_count` line with +2 and +4 lines 
https://github.com/Mithil467/mitype/blob/6c3b112ea9eb822b813fc2c9802d710a316e4a5b/mitype/app.py#L297-L299

**Comment by Mithil467** [comment]
Yes @jai-dewani that is correct.
But I think this can totally be avoided. Please check my [comment](https://github.com/Mithil467/mitype/issues/59#issuecomment-720056445) under the issue.

**Comment by Mithil467** [comment]
Appreciate the interest and efforts taken @sks147 :)
Thank you!

**Pull request closed without merging**
