### PR TITLE
Add accuracy stat

### LINKED ISSUE #16: Show more stats at end of each test
Currently we are only displaying the typing speed. We can add other attributes like `Accuracy` and `Time taken` nearby.

### PR DESCRIPTION
**Pull request by gudeliauskaspam**
- Add code that calculate accuracy and print it on screen.
- it was necessary to change some small parts of the original, for example: parameter lines_count, so that it was possible to print the new message in the correct layout.

This PR fixes #16

Tested with python version - 3.6.9

On operating system - Linux

### CODE REVIEW

**Comment by gudeliauskaspam** [comment]
I had some trouble with the command "isort --profile black ." it simply didnt worked for me.

**Comment by Mithil467** [comment]
Great work!
Can we display the accuracy with a precision of 2 digits after the decimal?

**Comment by gudeliauskaspam** [comment]
Of course, I will work on it right now.

**Comment by Mithil467** [comment]
User can reset the current test by pressing `esc` in the middle of a test.
Have a look at this function and try to make the required resets accordingly - https://github.com/Mithil467/mitype/blob/e059250a892b1a3e7f837d8b46243211949f5f91/mitype/app.py#L339

**Comment by Mithil467** [comment]
There are 2 more places where it would be great to display this new stat, history and at the bottom of the screen during replay.
Have a look at history.py. 

For displaying it during replay, you may make required changes here
https://github.com/Mithil467/mitype/blob/e059250a892b1a3e7f837d8b46243211949f5f91/mitype/app.py#L372

**Comment by gudeliauskaspam** [comment]
changes made!

**Comment by Mithil467** [comment]
Great! May you add this stat to history as well? Then we are good to merge this.

**Comment by gudeliauskaspam** [comment]
Its already there!

**Review by Mithil467 — APPROVED** [review]
Great work! Thank you for contributing. :smile:

**Pull request merged**
